#!/usr/bin/env php
<?php
use TheCodingMachine\WashingMachine\Commands\RunCommand;
use Symfony\Component\Console\Application;
use Interop\Container\ContainerInterface;

if (file_exists(__DIR__.'/vendor/autoload.php')) {
    require __DIR__.'/vendor/autoload.php';
} elseif (file_exists(__DIR__.'/../../../vendor/autoload.php')) {
    require __DIR__.'/../../../vendor/autoload.php';
} else {
    throw new \RuntimeException('Unable to find washingmachine dependencies. Please run composer install.');
}




$container = new \Mouf\Picotainer\Picotainer([
    RunCommand::class => function() {
        return new RunCommand();
    },
    Application::class => function(ContainerInterface $container) {
        $app = new Application('washingmachine');
        $app->add($container->get(RunCommand::class));
        return $app;
    }
]);

$app = $container->get(Application::class);
/* @var $app Application */
$app->run();
